version: '3.9'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: always
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    depends_on:
      - worker
      - rabbitmq

  worker:
    build: .
    command: celery -A myproject worker -l info -P solo
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: always
    depends_on:
      - web
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
