# Generated by Django 6.0.2 on 2026-05-20 20:23

import customer.models
import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0038_servicechargetier_commission_commission_structure_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=100)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech", "Technology"),
                            ("finance", "Finance"),
                            ("healthcare", "Healthcare"),
                            ("manufacturing", "Manufacturing"),
                            ("retail", "Retail"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("prospect", "Prospect"),
                            ("partner", "Partner"),
                            ("reseller", "Reseller"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("employees", models.IntegerField(blank=True, null=True)),
                ("address_street", models.CharField(blank=True, max_length=200)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_state", models.CharField(blank=True, max_length=100)),
                ("address_zipcode", models.CharField(blank=True, max_length=100)),
                ("address_country", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account (Company)",
                "verbose_name_plural": "Accounts (Companies)",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="customer.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact (Person)",
                "verbose_name_plural": "Contacts (People)",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("started_at", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(null=True)),
                ("employee_id", models.CharField(max_length=255, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CRMUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone_extension", models.CharField(blank=True, max_length=100)),
                ("is_sales_manager", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "CRM User",
                "verbose_name_plural": "CRM Users",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[customer.models.validate_nigerian_prefix],
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[customer.models.validate_account_number],
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        help_text="11-digit National Identification Number (NIN).",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIN must be exactly 11 digits.",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PBKDF2-hashed service password.  Never store plain text.",
                        max_length=256,
                    ),
                ),
                ("authenticated", models.BooleanField(default=False)),
                ("password_created", models.BooleanField(default=False)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_expiry", models.DateTimeField(blank=True, null=True)),
                ("otp_used", models.BooleanField(default=False)),
                ("password_attempts", models.IntegerField(default=0)),
                ("password_locked", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("nationality", models.CharField(default="Nigeria", max_length=50)),
                ("occupation", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["created_at", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("unqualified", "Unqualified"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web Form"),
                            ("referral", "Referral"),
                            ("partner", "Partner"),
                            ("purchased", "Purchased List"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(db_index=True, max_length=20)),
                (
                    "loan_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "credit_rating",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("credit_score", models.IntegerField(blank=True, null=True)),
                (
                    "credit_bureau_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "credit_bureau_last_checked",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("twitter_url", models.URLField(blank=True, default="")),
                ("tiktok_url", models.URLField(blank=True, default="")),
                ("facebook_followers", models.PositiveIntegerField(default=0)),
                ("facebook_posts_30d", models.PositiveIntegerField(default=0)),
                ("linkedin_connections", models.PositiveIntegerField(default=0)),
                ("linkedin_posts_30d", models.PositiveIntegerField(default=0)),
                ("instagram_followers", models.PositiveIntegerField(default=0)),
                ("instagram_posts_30d", models.PositiveIntegerField(default=0)),
                ("twitter_followers", models.PositiveIntegerField(default=0)),
                ("twitter_tweets_30d", models.PositiveIntegerField(default=0)),
                ("tiktok_followers", models.PositiveIntegerField(default=0)),
                ("tiktok_videos_30d", models.PositiveIntegerField(default=0)),
                (
                    "overall_engagement_score",
                    models.FloatField(
                        blank=True,
                        help_text="Normalised 0–100 composite engagement score derived by AI.",
                        null=True,
                    ),
                ),
                (
                    "loan_eligibility_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI-computed eligibility score 0–100.",
                        null=True,
                    ),
                ),
                (
                    "eligibility_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent (80–100)"),
                            ("good", "Good (60–79)"),
                            ("fair", "Fair (40–59)"),
                            ("poor", "Poor (0–39)"),
                        ],
                        default="",
                        help_text="Derived band based on eligibility score.",
                        max_length=20,
                    ),
                ),
                ("eligibility_notes", models.TextField(blank=True, default="")),
                (
                    "raw_ai_response",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full JSON blob returned by the LLM evaluation call.",
                    ),
                ),
                ("last_evaluated", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_profile",
                        to="customer.customer",
                        to_field="account_number",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Profile",
                "verbose_name_plural": "Loan Profiles",
            },
        ),
        migrations.CreateModel(
            name="LoanTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Bronze", "Bronze"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                        ],
                        default="Bronze",
                        max_length=20,
                    ),
                ),
                ("loan_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monthly_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly interest rate as a percentage (e.g. 2.5 for 2.5%)",
                        max_digits=5,
                    ),
                ),
                ("process_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("late_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tenor", models.IntegerField(help_text="Loan duration in months")),
                (
                    "monthly_repayment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_loan_due",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("bank", models.CharField(blank=True, max_length=100, null=True)),
                ("date_user_accept", models.DateTimeField()),
                ("disbursed", models.BooleanField(default=True)),
                (
                    "current_loan_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("highest_sentiment_comment", models.TextField(blank=True, null=True)),
                ("highest_sentiment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "highest_sentiment_channel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lowest_sentiment_comment", models.TextField(blank=True, null=True)),
                ("lowest_sentiment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "lowest_sentiment_channel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="customer.loanprofile",
                    ),
                ),
                (
                    "loan_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_tier",
                        to="customer.loantier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo representing this organizational unit",
                        null=True,
                        upload_to=customer.models.tenant_directory_path,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="Latitude coordinate of the organizational unit",
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="Longitude coordinate of the organizational unit",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.town"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LoanReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_account_number", models.CharField(max_length=20, unique=True)),
                (
                    "amount_collected",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("date_loan_booked", models.DateField()),
                ("last_repayment_date", models.DateField(blank=True, null=True)),
                ("loan_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "branch_booked",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_branch",
                to="customer.location",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="town_of_residence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_town",
                to="customer.location",
            ),
        ),
        migrations.CreateModel(
            name="BranchPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_customers", models.PositiveIntegerField()),
                ("total_transactions", models.PositiveIntegerField()),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("report_date", models.DateField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_user", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_attachments/"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customer.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("close_date", models.DateField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("qualification", "Qualification"),
                            ("needs_analysis", "Needs Analysis"),
                            ("value_proposition", "Value Proposition"),
                            ("id_decision_makers", "Identify Decision Makers"),
                            ("perception_analysis", "Perception Analysis"),
                            ("proposal_price", "Proposal/Price Quote"),
                            ("negotiation_review", "Negotiation/Review"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="qualification",
                        max_length=100,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        choices=[
                            (0, "0%"),
                            (10, "10%"),
                            (20, "20%"),
                            (30, "30%"),
                            (40, "40%"),
                            (50, "50%"),
                            (60, "60%"),
                            (70, "70%"),
                            (80, "80%"),
                            (90, "90%"),
                            (100, "100%"),
                        ],
                        default=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pending_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("qualification", "Qualification"),
                            ("needs_analysis", "Needs Analysis"),
                            ("value_proposition", "Value Proposition"),
                            ("id_decision_makers", "Identify Decision Makers"),
                            ("perception_analysis", "Perception Analysis"),
                            ("proposal_price", "Proposal/Price Quote"),
                            ("negotiation_review", "Negotiation/Review"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="customer.account",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="customer.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_opportunities_vCRM",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_opportunities_vCRM",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity (Sales Deal)",
                "verbose_name_plural": "Opportunities (Sales Deals)",
            },
        ),
        migrations.CreateModel(
            name="PasswordSetupToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_setup_tokens",
                        to="customer.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Setup Token",
                "verbose_name_plural": "Password Setup Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="standard", max_length=100)),
                ("is_hum_agent_allow_prompt", models.TextField(blank=True, null=True)),
                ("no_hum_agent_allow_prompt", models.TextField(blank=True, null=True)),
                ("summary_prompt", models.TextField(blank=True, null=True)),
                ("agent_prompt", models.TextField(blank=True, null=True)),
                ("global_answer_prompt", models.TextField(blank=True, null=True)),
                ("tool_intent_map", models.JSONField(blank=True, null=True)),
                ("biller_items", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tenant_AI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_website",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_knowledge_base",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tenant_text", models.TextField(blank=True, null=True)),
                ("tenant_document", models.TextField(blank=True, null=True)),
                ("is_hum_agent_allow", models.BooleanField(default=True)),
                ("conf_level", models.IntegerField(default=40)),
                ("sentiment_threshold", models.FloatField(default=0.0)),
                ("ticket_type", models.JSONField(default=list)),
                (
                    "message_tone",
                    models.CharField(default="Professional", max_length=20),
                ),
                (
                    "chatbot_greeting",
                    models.TextField(default="How can I assist you today?"),
                ),
                (
                    "agent_node_prompt",
                    models.TextField(blank=True, default="...", null=True),
                ),
                ("final_answer_prompt", models.TextField(blank=True, null=True)),
                ("summary_prompt", models.TextField(blank=True, null=True)),
                ("prompt_type", models.CharField(default="standard", max_length=50)),
                ("db_uri", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.prompt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                            ("airtime", "Airtime Purchase"),
                            ("loan", "Loan Disbursement"),
                            ("bill_payment", "Bill Payment"),
                            ("balance_enquiry", "Balance Enquiry"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transaction_channel",
                    models.CharField(
                        choices=[
                            ("atm", "ATM"),
                            ("pos", "POS"),
                            ("branch", "Branch"),
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "charge_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="VFD transaction reference for the ₦10 debit.",
                        max_length=100,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_otps",
                        to="customer.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "is_used", "expires_at"],
                        name="customer_pa_custome_0d5bfe_idx",
                    )
                ],
            },
        ),
    ]
