# Generated by Django 5.2.5 on 2025-09-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='delivery_time_days',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='service_type',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('wash', 'Washing'), ('iron', 'Ironing'), ('dry_clean', 'Dry Cleaning')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time_days', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
            options={
                'unique_together': {('category', 'service_type')},
            },
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.service'),
        ),
    ]
