# Generated by Django 5.2.5 on 2025-09-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('wash_fold', 'Wash & Fold'), ('dry_clean', 'Dry Cleaning'), ('ironing', 'Ironing')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_time_days',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('category', 'service_type')},
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='myapp.service'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', 'Pending Dispatch'), ('in_transit', 'In Transit'), ('at_facility', 'At Facility'), ('washing', 'Washing'), ('drying', 'Drying'), ('ironing', 'Ironing'), ('packaging', 'Packaging'), ('ready_for_pickup', 'Ready for Pickup/Dispatch'), ('completed', 'Completed')], default='pending_dispatch', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myapp.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
