# Generated by Django 5.2.5 on 2026-03-19 07:06

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_customuser_options_remove_customuser_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Dignity",
                        help_text="Tenant name, e.g., Dignity",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="DMC",
                        help_text="Short unique code for the tenant (e.g., MSFT)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subdomain", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand_name",
                    models.CharField(
                        default="Dignity",
                        help_text="Brand name , e.g., Dignity",
                        max_length=210,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Primary logo for the tenant (displayed in header)",
                        null=True,
                        upload_to=myapp.models.tenant_directory_path,
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Tenant-specific favicon",
                        null=True,
                        upload_to=myapp.models.tenant_directory_path,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4f46e5",
                        help_text="Brand primary color (Hex), e.g., #4f46e5",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Brand secondary color (Hex), e.g., #6366f1",
                        max_length=7,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="'Inter', sans-serif",
                        help_text="CSS Font family for the tenant",
                        max_length=255,
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True, help_text="Custom CSS overrides for this tenant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tenant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tenant",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tenant",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tenant",
            ),
        ),
    ]
