# Generated by Django 5.2.5 on 2025-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_remove_laundryitem_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryitem',
            name='color',
            field=models.CharField(default='red', max_length=100),
            preserve_default=False,
        ),
    ]
