# Generated by Django 5.2.5 on 2026-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_tenant_comment_tenant_order_tenant_orderitem_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.SlugField(
                default="127.0.0.1",
                help_text="Subdomain for the tenant (e.g., dignity)",
                unique=True,
            ),
        ),
    ]
