# Generated by Django 5.2.5 on 2026-03-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_tenant_subdomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.CharField(
                default="127.0.0.1",
                help_text="Subdomain for the tenant (e.g., dignity)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
