# Generated by Django 5.2.5 on 2025-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_servicetype_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
