# Generated by Django 5.2.5 on 2026-03-19 10:40

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("myapp", "0006_alter_customuser_options_customuser_is_buyer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="service",
            new_name="package",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[myapp.models.validate_nigerian_phone],
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deputy_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Deputy head for automatic delegation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deputy_for",
                        to="myapp.employee",
                    ),
                ),
                (
                    "line_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downline",
                        to="myapp.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Links to the Django user account for login.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Record",
                "verbose_name_plural": "Employee Records",
                "ordering": ["user__name"],
            },
        ),
        migrations.RenameModel(
            old_name="Service",
            new_name="Package",
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name of the workflow, e.g., 'Annual Leave Process'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Defines code of the workflow eg 'leave-approval'"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="myapp.package",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Record",
                "verbose_name_plural": "Workflow Records",
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closure_ref",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rejected_for_amendment", "Rejected for Amendment"),
                            ("closed", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="closed",
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_workflows",
                        to="myapp.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.workflow"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action_description", models.TextField()),
                (
                    "is_closed",
                    models.BooleanField(
                        blank=True,
                        help_text="True if action was an closed, False if rejection, None otherwise",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="myapp.workflowinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("pending_dispatch", "Pending Dispatch"),
                            ("in_transit", "In Transit"),
                            ("at_facility", "At Facility"),
                            ("washing", "Washing"),
                            ("drying", "Drying"),
                            ("ironing", "Ironing"),
                            ("packaging", "Packaging"),
                            ("ready_for_pickup", "Ready for Pickup/Dispatch"),
                            ("completed", "Completed"),
                        ],
                        help_text="Descriptive name of the stage, e.g., 'Manager Approval'",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order of execution (e.g., 1, 2, 3)"
                    ),
                ),
                (
                    "turnaround_time",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Maximum hours allowed for action before escalation.",
                    ),
                ),
                ("is_final_stage", models.BooleanField(default=False)),
                ("completed_status", models.BooleanField(default=False)),
                (
                    "responsible_officer",
                    models.ForeignKey(
                        help_text="The employee responsible for handling this stage.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approver_stages",
                        to="myapp.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="myapp.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("workflow", "sequence", "tenant")},
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="current_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="myapp.workflowstage"
            ),
        ),
    ]
