# Generated by Django 5.2.5 on 2025-09-11 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customerrequest_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomerRequest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Customer Review'), ('accepted', 'Accepted by Customer'), ('commented', 'Commented by Customer'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='pending_review', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
