# Generated by Django 5.2.5 on 2026-03-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_servicechoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstage",
            name="name",
            field=models.ForeignKey(
                blank=True,
                help_text="Descriptive name of the stage, e.g., 'Manager Approval'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.servicechoices",
            ),
        ),
    ]
