# Generated by Django 5.2.5 on 2026-03-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_workflowstage_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstage",
            name="name",
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="service_action",
            field=models.ForeignKey(
                blank=True,
                help_text="Descriptive name of the stage, e.g., 'In Washing'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.servicechoices",
            ),
        ),
    ]
