# Generated by Django 5.2.5 on 2026-03-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_remove_workflowstage_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
