# Generated by Django 5.2.5 on 2026-03-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_premiumclient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="has_comment",
            new_name="is_confirmed",
        ),
    ]
