# Generated by Django 5.2.5 on 2026-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_rename_has_comment_order_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="has_comment_from_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="has_invoice_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="has_payment_received",
            field=models.BooleanField(default=False),
        ),
    ]
