# Generated by Django 5.2.5 on 2026-03-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_order_has_comment_from_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_confirmed",
            new_name="has_confirmation_received",
        ),
    ]
