# Generated by Django 5.2.5 on 2026-03-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_rename_is_confirmed_order_has_confirmation_received"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_code",
        ),
        migrations.RemoveField(
            model_name="workflowinstance",
            name="job_status",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="qr_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="QR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "Unused"),
                            ("assigned", "Assigned"),
                            ("invalid", "Invalid"),
                        ],
                        default="unused",
                        max_length=20,
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="myapp.orderitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(blank=True, max_length=50, null=True)),
                ("to_stage", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        help_text="Accept, Reject, Escalate, etc.", max_length=50
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to="myapp.employee",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_history",
                        to="myapp.orderitem",
                    ),
                ),
                (
                    "previous_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_actions",
                        to="myapp.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
