# Generated by Django 5.2.5 on 2026-03-20 17:43

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_remove_order_order_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_code",
            field=models.CharField(
                default=myapp.models.generate_order_code, max_length=12
            ),
        ),
    ]
