# Generated by Django 5.2.5 on 2026-03-20 17:51

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_order_order_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qr",
            name="order_item",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(
                default=myapp.models.generate_order_code, max_length=12, unique=True
            ),
        ),
    ]
