# Generated by Django 5.2.5 on 2026-03-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_qr_order_item_alter_order_order_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="comment",
            name="actor",
            field=models.CharField(
                choices=[("customer", "Csutomer"), ("staff", "Staff")],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="order",
            field=models.ForeignKey(
                default="missing_id",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="comments",
                to="myapp.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("invoice_sent", "Invoice Sent"),
                    ("commented", "Commented"),
                    ("confirmed", "Confirmed Order"),
                    ("in_progress", "In Progress"),
                    ("paid", "Paid"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
