# Generated by Django 5.2.5 on 2026-03-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_comment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="myapp.order",
            ),
        ),
    ]
