# Generated by Django 5.2.5 on 2026-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_comment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
