# Generated by Django 5.2.5 on 2026-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_order_work_initiator_orderitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatched_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="qr_secure_token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="received_by_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="received_by_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sentiment_analysis",
            field=models.CharField(
                blank=True,
                help_text="Sentiment analysis label/score",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("invoice_sent", "Invoice Sent"),
                    ("commented", "Commented"),
                    ("confirmed", "Confirmed Order"),
                    ("in_progress", "In Progress"),
                    ("ready_for_dispatch", "Ready for Dispatch"),
                    ("awaiting_dispatch", "Awaiting Dispatch"),
                    ("assigned_to_dispatcher", "Assigned to Dispatcher"),
                    ("paid", "Paid"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=120,
            ),
        ),
    ]
