# Generated by Django 6.0.3 on 2026-04-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_customuser_latitude_customuser_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_number",
            field=models.CharField(
                default="+2349068770054",
                help_text="WhatsApp phone number",
                max_length=20,
            ),
        ),
    ]
