# Generated by Django 6.0.3 on 2026-04-18 12:06

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_tenant_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="deliverypricing",
            name="max_km",
        ),
        migrations.RemoveField(
            model_name="deliverypricing",
            name="min_km",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="component_restrictions",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="custom_css",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="font_family",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="location_lat",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="location_lng",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="northeast_lat",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="northeast_lng",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="southwest_lat",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="southwest_lng",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="strict_bounds",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="whatsapp_number",
        ),
        migrations.AlterField(
            model_name="package",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="myapp.servicechoices",
            ),
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="deliverypricing",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_prices",
                to="myapp.cluster",
            ),
        ),
        migrations.CreateModel(
            name="TenantAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="Dignity",
                        help_text="Brand name , e.g., Dignity",
                        max_length=210,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Primary logo for the tenant (displayed in header)",
                        null=True,
                        upload_to=myapp.models.tenant_directory_path,
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Tenant-specific favicon",
                        null=True,
                        upload_to=myapp.models.tenant_directory_path,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4f46e5",
                        help_text="Brand primary color (Hex), e.g., #4f46e5",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Brand secondary color (Hex), e.g., #6366f1",
                        max_length=7,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="'Inter', sans-serif",
                        help_text="CSS Font family for the tenant",
                        max_length=255,
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True, help_text="Custom CSS overrides for this tenant"
                    ),
                ),
                (
                    "component_restrictions",
                    models.CharField(
                        default="NG",
                        help_text="ISO country code for Places API",
                        max_length=50,
                    ),
                ),
                ("strict_bounds", models.BooleanField(default=True)),
                (
                    "southwest_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "southwest_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "northeast_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "northeast_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+2349068770054",
                        help_text="WhatsApp phone number",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute",
                        to="myapp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towns",
                        to="myapp.state",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("name", "state")},
            },
        ),
        migrations.AddField(
            model_name="cluster",
            name="towns",
            field=models.ManyToManyField(related_name="clusters", to="myapp.town"),
        ),
    ]
