# Generated by Django 6.0.3 on 2026-04-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_state_remove_deliverypricing_max_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.state",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="town",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.town",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="myapp.state",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_town",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="myapp.town",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_orders",
                to="myapp.state",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="town",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_orders",
                to="myapp.town",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True, help_text="House/Street address", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True, help_text="House/Street address", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_address",
            field=models.CharField(
                blank=True, help_text="House/Street address", max_length=255, null=True
            ),
        ),
    ]
