# Generated by Django 6.0.3 on 2026-04-19 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_customuser_state_customuser_town_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowhistory",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="qr_initiator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qr_assigned_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="work_initiator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="initiated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecord",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="responsible_officer",
            field=models.ForeignKey(
                help_text="The employee responsible for handling this stage.",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approver_stages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowhistory",
            name="previous_actor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name="cluster",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="customuser",
            name="deputy_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Deputy head for automatic delegation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deputy_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="line_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downline",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantattribute",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Tenant physical address",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cluster",
            unique_together={("name", "tenant")},
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
