# Generated by Django 6.0.3 on 2026-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_alter_workflowhistory_actor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary email for the tenant contact",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Primary phone for the tenant contact",
                max_length=20,
                null=True,
            ),
        ),
    ]
