# Generated by Django 6.0.3 on 2026-04-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_tenant_email_tenant_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"ordering": ["category", "service_type"]},
        ),
    ]
