# Generated by Django 6.0.3 on 2026-04-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0032_alter_package_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Actual date/time the order was delivered",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reschedule_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Customer-requested reschedule date for delivery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color_custom",
            field=models.CharField(
                blank=True,
                help_text="Custom color name when 'Other' is selected",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of this item"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user (superuser/aggregator) who created this tenant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "hex_code",
                    models.CharField(
                        default="#000000",
                        help_text="Hex color code, e.g. #FF5733",
                        max_length=7,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "tenant")},
            },
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="myapp.color",
            ),
        ),
    ]
