# Generated by Django 6.0.2 on 2026-04-22 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0033_color_quantity_reschedule_tenant_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="qr",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qr",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time to pick up your Laundry",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reschedule_date",
            field=models.DateTimeField(
                blank=True, help_text="Date and time for rescheduling", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="State to pick up from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_orders",
                to="myapp.state",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="town",
            field=models.ForeignKey(
                blank=True,
                help_text="Town to pick up from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_orders",
                to="myapp.town",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="category",
            field=models.ForeignKey(
                help_text="Category of service",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="myapp.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Price of service", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of service",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="myapp.servicechoices",
            ),
        ),
    ]
