# Generated by Django 6.0.2 on 2026-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_qr_created_by_qr_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="password",
            field=models.CharField(
                blank=True, help_text="SMTP email password", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="vectra_email",
            field=models.EmailField(
                blank=True, help_text="SMTP email username", max_length=254, null=True
            ),
        ),
    ]
