# Generated by Django 6.0.2 on 2026-05-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_tenant_password_tenant_vectra_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantattribute",
            name="operation_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of operation days, e.g., ['Mon', 'Tue']",
            ),
        ),
        migrations.AddField(
            model_name="tenantattribute",
            name="operation_hours",
            field=models.CharField(
                blank=True,
                help_text="e.g., 8:00 AM - 8:00 PM",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LandingCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Carousel background image",
                        upload_to="landing/carousel/",
                    ),
                ),
                ("title", models.CharField(help_text="Main heading", max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "transition_speed",
                    models.PositiveIntegerField(
                        default=5000, help_text="Speed in ms (e.g. 5000 for 5s)"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing/commitment/"
                    ),
                ),
                (
                    "committed_to",
                    models.CharField(
                        default="Committed to Garment Care and Our Community",
                        max_length=200,
                    ),
                ),
                ("we_believe", models.TextField(help_text="We believe... text")),
                (
                    "eco_friendly",
                    models.TextField(
                        help_text="Non-toxic Detergents: Safe for sensitive skin and the environment."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingCustomerStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("stars", models.PositiveSmallIntegerField(default=5)),
                ("is_verified", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingPricingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g. Wash & Fold", max_length=100),
                ),
                ("is_popular", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(
                        help_text="e.g. Perfect for everyday wear", max_length=255
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "features",
                    models.JSONField(default=list, help_text="List of features"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Laundry Made Simple, Fresh & Fast", max_length=255
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Experience premium laundry care with the touch of a button. We handle the dirty work so you can focus on what matters."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_text",
                    models.CharField(help_text="e.g. Free Pickup", max_length=100),
                ),
                (
                    "value_subtext",
                    models.CharField(
                        help_text="e.g. From your doorstep", max_length=200
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-truck",
                        help_text="FontAwesome class e.g. fas fa-truck",
                        max_length=50,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
