# Generated by Django 6.0.2 on 2026-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0036_tenantattribute_operation_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="servicechoices",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("category", "service_type", "tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="servicecategory",
            unique_together={("name", "tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="servicechoices",
            unique_together={("name", "tenant")},
        ),
    ]
