# Generated by Django 6.0.2 on 2026-05-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0037_alter_servicecategory_name_alter_servicechoices_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceChargeTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "charge",
                    models.IntegerField(help_text="Charge percentage (e.g. 3 for 3%)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_order_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("service_charge_percentage", models.IntegerField()),
                (
                    "dignity_portion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tenant_share", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "aggregator_commission_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "dsa_commission_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "net_dignity_commission",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aggregator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aggregator_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dsa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsa_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_record",
                        to="myapp.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Commission_Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aggregator_commission",
                    models.IntegerField(help_text="Percentage of Dignity's charge"),
                ),
                (
                    "dignity_commission",
                    models.IntegerField(help_text="Percentage of Dignity's charge"),
                ),
                (
                    "dsa_commission",
                    models.IntegerField(editable=False, help_text="Auto-calculated"),
                ),
                (
                    "aggregator",
                    models.OneToOneField(
                        limit_choices_to={"groups__name": "Aggregator"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tenant",
            name="service_charge_tier",
            field=models.ForeignKey(
                blank=True,
                help_text="Service charge tier applied to this tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.servicechargetier",
            ),
        ),
    ]
