# Generated by Django 6.0.2 on 2026-05-21 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0038_servicechargetier_commission_commission_structure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "transformer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("msisdn", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PowerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.BigIntegerField()),
                ("peak_a0", models.IntegerField(default=0)),
                (
                    "server_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("msisdn", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "feeder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="myapp.feeder",
                    ),
                ),
            ],
        ),
    ]
