# Generated by Django 6.0.3 on 2026-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0039_feeder_powerstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeder",
            name="band",
            field=models.CharField(
                choices=[
                    ("A", "Band A"),
                    ("B", "Band B"),
                    ("C", "Band C"),
                    ("D", "Band D"),
                    ("E", "Band E"),
                    ("F", "Band F"),
                ],
                default="A",
                max_length=1,
            ),
        ),
    ]
