# Generated by Django 6.0.2 on 2026-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0040_feeder_band"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feeder",
            old_name="contact_phone",
            new_name="custodian_phone",
        ),
        migrations.RemoveField(
            model_name="powerstatus",
            name="contact_phone",
        ),
        migrations.AddField(
            model_name="feeder",
            name="custodian_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="feeder",
            name="registered_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="feeder",
            name="sim_serial",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="sim_serial",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
