# Generated by Django 6.0.2 on 2026-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0041_rename_contact_phone_feeder_custodian_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeder",
            name="primary_recipient",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated whatsapp numbers and/or group IDs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feeder",
            name="transformer_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
