# Generated by Django 6.0.2 on 2026-07-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0042_feeder_primary_recipient_feeder_transformer_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="School_tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=255)),
                ("evolution_instance", models.CharField(max_length=255)),
                ("evolution_api", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_firstname", models.CharField(max_length=255)),
                ("student_lastname", models.CharField(max_length=255)),
                ("student_id", models.CharField(max_length=100)),
                ("student_email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("guardian_name", models.CharField(max_length=255)),
                ("guardian_phone", models.CharField(max_length=20)),
                ("guardian_email", models.EmailField(max_length=254)),
                (
                    "student_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="myapp.school_tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out")], max_length=10
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="myapp.student_profile",
                    ),
                ),
            ],
        ),
    ]
