# Generated by Django 6.0.2 on 2026-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0043_school_tenant_student_profile_attendance_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="school_tenant",
            name="tenant_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
