# Generated by Django 6.0.2 on 2026-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0044_school_tenant_tenant_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeder",
            name="whatsapp_group",
            field=models.CharField(
                blank=True,
                default="120363410539285836@g.us",
                help_text="WhatsApp group ID for power alerts (e.g. 120363410539285836@g.us)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feeder",
            name="whatsapp_primary",
            field=models.CharField(
                blank=True,
                default="2348021299221",
                help_text="Primary WhatsApp number to receive power alerts (e.g. 2348021299221)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="dt",
            field=models.CharField(
                blank=True,
                help_text="Device type identifier, e.g. PEARL",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="stat_b",
            field=models.CharField(
                blank=True,
                help_text="Blue phase status: ON or OFF",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="stat_r",
            field=models.CharField(
                blank=True,
                help_text="Red phase status: ON or OFF",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="stat_y",
            field=models.CharField(
                blank=True,
                help_text="Yellow phase status: ON or OFF",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="volt_b",
            field=models.FloatField(
                default=0.0, help_text="Blue phase RMS voltage (V)"
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="volt_r",
            field=models.FloatField(default=0.0, help_text="Red phase RMS voltage (V)"),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="volt_y",
            field=models.FloatField(
                default=0.0, help_text="Yellow phase RMS voltage (V)"
            ),
        ),
        migrations.AlterField(
            model_name="feeder",
            name="primary_recipient",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated WhatsApp numbers and/or group IDs (legacy / fallback)",
                null=True,
            ),
        ),
    ]
