# Generated by Django 6.0.2 on 2026-10-05 19:31

import uuid
from django.db import migrations, models


def populate_uuid(apps, schema_editor):
    PowerStatus = apps.get_model("myapp", "PowerStatus")
    try:
        schema_editor.execute("UPDATE myapp_powerstatus SET event_id = gen_random_uuid()")
    except Exception:
        for row in PowerStatus.objects.all().iterator():
            row.event_id = uuid.uuid4()
            row.save(update_fields=["event_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0046_alter_feeder_whatsapp_primary_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerstatus",
            name="event_id",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                null=True,
            ),
        ),
        migrations.RunPython(populate_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="powerstatus",
            name="event_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="powerstatus",
            name="whatsapp_status",
            field=models.CharField(
                choices=[("delivered", "Delivered"), ("undelivered", "Undelivered")],
                db_index=True,
                default="undelivered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feeder",
            name="whatsapp_group",
            field=models.CharField(
                blank=True,
                default="120363410539285836@g.us, 120363429032532411@g.us, 120363429460546485@g.us",
                help_text="Comma-separated WhatsApp group IDs (e.g. 120363410539285836@g.us, 120363429032532411@g.us)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feeder",
            name="whatsapp_primary",
            field=models.CharField(
                blank=True,
                default="2348021299221, 2349068770054",
                help_text="Comma-separated primary WhatsApp numbers (e.g. 2348021299221, 2349068770054)",
                max_length=255,
                null=True,
            ),
        ),
    ]
